version: '3.8'
services:
  springapp:
    image: ravshan1972/spring-boot-mongo-docker:VERSION
    container_name: springapp-docker
    ports:
    - 9090:8080
    environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=devdb@1306
    networks:
      - springappnetwork
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo-docker
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb
      - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
      - mongodb:/data/db
    networks:
      - springappnetwork
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
volumes:
  mongodb:
    name: "mongodb"
    #driver: local
    external: true
networks:
  springappnetwork:
    name: "springappnetwork"
    #driver: local/bridge/overlay
    external: true
