version: '3.8'
services:
  springapp:
    container_name: springapp
    image: ravshan1972/spring-boot-mongo-docker:VERSION
    ports:
    - 9090:8080
    environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=devdb@1306
    networks:
      - springappnetwork
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb
      - MONGO_INITDB_ROOT_PASSWORD=devdb@1306
    volumes:
      - mongodb:/data/db
    networks:
      - springappnetwork
volumes:
  mongodb:
    name: mongodb
    driver: local
networks:
  springappnetwork:
    name: springappnetwork
    #driver: bridge
    external: true
