version: '3.8'
services:
  springapp:
    image: ravshan1972/spring-boot-mongo-docker:VERSION
    container_name: springapp
    ports:
    - 9090:8080
    environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=devdb@1306
    networks:
      - springappnetwork
    depends_on:
      - mongo
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devdb
      - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork
volumes:
  mongodb:
    name: mongodb
    driver: local
networks:
  springappnetwork:
    name: springappnetwork
    #driver: bridge
    external: true
